local opt = vim.opt

opt.completeopt = {'menuone', 'noinsert', 'noselect'}
opt.expandtab = true
opt.hidden = true
opt.ignorecase = true
opt.wildmode= { "list", "longest"}
opt.incsearch = true
opt.smartindent = true
opt.shiftwidth = 2
opt.tabstop = 2
opt.softtabstop=2
opt.expandtab = true
opt.textwidth = 100
opt.mouse = "a"
opt.signcolumn = "yes"
opt.wrap = true
opt.linebreak = true
opt.colorcolumn = "80"
opt.swapfile = false
opt.clipboard = "unnamedplus"
